language: android
android:
    components:
        - tools
        - platform-tools
        - build-tools-26.0.2
        - android-26
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
script:
    - ./gradlew build
before_install:
    - chmod +x gradlew
branches:
    only:
        - develop
               
                